heat_template_version: 2015-10-15

description: Network (Reusing existing)

parameters:
  stack_name:
    type: string
  key_value:
    type: string
  public_net:
    type: string
    description: ID or name of public network for which floating IP addresses will be allocated
  private_net:
    type: string
    description: Private network
  private_net_cidr:
    type: string
    description: Private network address (CIDR notation)
    default: 192.168.10.0/24
  private_net_pool_start:
    type: string
    description: Start of private network IP address allocation pool
    default: 192.168.10.90
  private_net_pool_end:
    type: string
    description: End of private network IP address allocation pool
    default: 192.168.10.200

resources:
  key_pair:
    type: OS::Nova::KeyPair
    properties:
      name: { get_param: stack_name }
      public_key: { get_param: key_value }
      save_private_key: false
  security_group:
    type: OS::Neutron::SecurityGroup
    properties:
      name: { get_param: stack_name }
      description: Security group
      rules:
        - protocol: tcp
          remote_ip_prefix: 0.0.0.0/0
        - protocol: udp
          remote_ip_prefix: 0.0.0.0/0
        - protocol: icmp
          remote_ip_prefix: 0.0.0.0/0

outputs:
  private_net_name:
    value: { get_param: private_net }
  security_group:
    value: { get_param: stack_name }
