heat_template_version: 2015-10-15

description: Server cluster (autoscaling)

parameters:
  admin_net:
    type: string
  private_net:
    type: string
  virtual_dns:
    type: string
  security_group:
    type: string
  key_pair:
    type: string
  config_host:
    type: string
  config_password:
    type: string
  instance_os:
    type: string
  instance_flavor:
    type: string
  instance_image:
    type: string
  instance_zone:
    type: string
  volume_type:
    type: string

resources:
  server_scaling_group:
    type: OS::Heat::AutoScalingGroup
    properties:
      min_size: 1
      max_size: 5
      resource:
        type: MCP::ScaleClusterMember
        properties:
          private_net: { get_param: private_net }
          virtual_dns: { get_param: virtual_dns }
          key_pair: { get_param: key_pair }
          security_group: { get_param: security_group }
          config_host: { get_param: config_host }
          config_password: { get_param: config_password }
          instance_os: { get_param: instance_os }
          instance_flavor: { get_param: instance_flavor }
          instance_image: { get_param: instance_image }
          instance_zone:  { get_param: instance_zone }
          instance_class: { get_param: instance_class }
          instance_name: { get_param: instance01_name }
          volume_type: { get_param: volume_type }
          cluster_name: { get_param: cluster_name }
          domain_name: { get_param: domain_name }
          balancer_pool: { get_resource: load_balancer_pool }
          metadata: { "metering.stack": { get_param: "OS::stack_id"} }
  cluster_scaleup_policy:
    type: OS::Heat::ScalingPolicy
    properties:
      adjustment_type: change_in_capacity
      auto_scaling_group_id: { get_resource: cluster_scaling_group }
      cooldown: 60
      scaling_adjustment: 1
  cluster_scaledown_policy:
    type: OS::Heat::ScalingPolicy
    properties:
      adjustment_type: change_in_capacity
      auto_scaling_group_id: { get_resource: cluster_scaling_group }
      cooldown: 60
      scaling_adjustment: -1
  cpu_alarm_high:
    type: OS::Ceilometer::Alarm
    properties:
      description: Scale-up if the average CPU > 50% for 1 minute
      meter_name: cpu_util
      statistic: avg
      period: 120
      evaluation_periods: 1
      threshold: 50
      alarm_actions:
        - { get_attr: [cluster_scaleup_policy, alarm_url] }
      matching_metadata: { 'metadata.user_metadata.stack': {get_param: "OS::stack_id"} }
      comparison_operator: gt
  cpu_alarm_low:
    type: OS::Ceilometer::Alarm
    properties:
      description: Scale-down if the average CPU < 15% for 10 minutes
      meter_name: cpu_util
      statistic: avg
      period: 120
      evaluation_periods: 1
      threshold: 15
      alarm_actions:
        - { get_attr: [cluster_scaledown_policy, alarm_url] }
      matching_metadata: { 'metadata.user_metadata.stack': {get_param: "OS::stack_id"} }
      comparison_operator: lt
  monitor:
    type: OS::Neutron::HealthMonitor
    properties:
      type: TCP
      delay: 5
      max_retries: 5
      timeout: 5
  load_balancer_pool:
    type: OS::Neutron::Pool
    properties:
      protocol: HTTP
      monitors: [{ get_resource: monitor }]
      subnet_id: { get_resource: vip_subnet }
      lb_method: ROUND_ROBIN
      vip:
        protocol_port: 80
  load_balancer:
    type: OS::Neutron::LoadBalancer
    properties:
      protocol_port: 80
      pool_id: { get_resource: load_balancer_pool }
