heat_template_version: 2013-05-23

description: OpenStack 3 controllers fragment

parameters:

  public_net:
    type: string
  private_net:
    type: string
  private_net:
    type: string
  security_group:
    type: string
  key_pair:
    type: string
  key_private:
    type: string
    hidden: true
  key_value:
    type: string

  cluster_vip_address:
    type: string
    default: 172.16.10.254

  reclass_address:
    type: string
  reclass_branch:
    type: string
    default: master

  instance_flavor:
    type: string
  instance_image:
    type: string
  instance_zone:
    type: string

  ci01_name:
    type: string
  ci02_name:
    type: string
  ci03_name:
    type: string

  ci01_address:
    type: string
    default: 172.16.10.11
  ci02_address:
    type: string
    default: 172.16.10.12
  ci03_address:
    type: string
    default: 172.16.10.13

resources:
  ci01_floating_ip:
    type: OS::Nova::FloatingIP
    properties:
      pool: { get_param: public_net }
  ci01_floating_ip_association:
    type: OS::Nova::FloatingIPAssociation
    properties:
      floating_ip: { get_resource: ci01_floating_ip }
      server_id: { get_resource: ci01_instance }
  ci01_private_port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_param: private_net }
      fixed_ips:
        - ip_address: { get_param: ci01_address }
      allowed_address_pairs:
        - ip_address: { get_param: cluster_vip_address }
      security_groups:
        - default
        - { get_param: security_group }
  ci01_wait_handle:
    type: OS::Heat::WaitConditionHandle
  ci01_wait_condition:
    type: OS::Heat::WaitCondition
    properties:
      handle: {get_resource: ci01_wait_handle}
      timeout: 3600
  ci01_instance:
    type: OS::Nova::Server
    properties:
      image: { get_param: instance_image }
      flavor: { get_param: instance_flavor }
      key_name: { get_param: key_pair }
      name: { get_param: ci01_name }
      availability_zone: { get_param: instance_zone }
      networks:
      - port: { get_resource: ci01_private_port }
      user_data_format: RAW
      user_data:
        str_replace:
          template: |
            #!/bin/bash
            # Redirect all outputs
            exec > >(tee -i /tmp/mk-bootstrap.log) 2>&1
            set -x
            echo "Preparing base OS ..."
            echo -e "nameserver 172.18.176.4\nnameserver 8.8.8.8" >/etc/resolv.conf

            which wget >/dev/null || (apt-get update; apt-get install -y wget)

            echo "deb [arch=amd64] http://apt.tcpcloud.eu/nightly/ xenial main security extra tcp" > /etc/apt/sources.list
            wget -O - http://apt.tcpcloud.eu/public.gpg | apt-key add -

            echo "deb http://repo.saltstack.com/apt/ubuntu/16.04/amd64/2016.3 xenial main" > /etc/apt/sources.list.d/saltstack.list
            wget -O - https://repo.saltstack.com/apt/ubuntu/16.04/amd64/2016.3/SALTSTACK-GPG-KEY.pub | apt-key add -

            apt-get clean
            apt-get update

            echo "Installing salt master ..."
            apt-get install -y reclass
            apt-get install -y salt-master

            [ ! -d /root/.ssh ] && mkdir -p /root/.ssh
            cat << 'EOF' > /root/.ssh/id_rsa
            $key_private
            EOF
            chmod 400 /root/.ssh/id_rsa

            # Setup the private key for cloning the reclass model (optional)
            if [[ "$reclass_private_key" != "" ]]; then
                cat << 'EOF' > /root/.ssh/reclass_key
            $reclass_private_key
            EOF
                chmod 400 /root/.ssh/reclass_key
                cat << 'EOF' >> /root/.ssh/config
            Host github.com
            IdentityFile /root/.ssh/reclass_key
            IdentitiesOnly yes
            EOF
            fi

            cat << 'EOF' > /etc/salt/master.d/master.conf
            file_roots:
              base:
              - /usr/share/salt-formulas/env
            pillar_opts: False
            open_mode: True
            reclass: &reclass
              storage_type: yaml_fs
              inventory_base_uri: /srv/salt/reclass
            ext_pillar:
              - reclass: *reclass
            master_tops:
              reclass: *reclass
            EOF

            echo "Configuring reclass ..."
            ssh-keyscan -H github.com >> ~/.ssh/known_hosts
            git clone -b $reclass_branch --recurse-submodules $reclass_address /srv/salt/reclass
            mkdir -p /srv/salt/reclass/classes/service

            FORMULA_PATH=${FORMULA_PATH:-/usr/share/salt-formulas}
            FORMULA_REPOSITORY=${FORMULA_REPOSITORY:-deb [arch=amd64] http://apt.tcpcloud.eu/nightly/ xenial tcp-salt}
            FORMULA_GPG=${FORMULA_GPG:-http://apt.tcpcloud.eu/public.gpg}

            echo "Configuring salt master formulas ..."
            which wget > /dev/null || (apt-get update; apt-get install -y wget)

            echo "${FORMULA_REPOSITORY}" > /etc/apt/sources.list.d/tcpcloud_salt.list
            wget -O - "${FORMULA_GPG}" | apt-key add -

            apt-get clean
            apt-get update

            [ ! -d /srv/salt/reclass/classes/service ] && mkdir -p /srv/salt/reclass/classes/service

            apt-get install -y salt-formula-*
            for formula in ${FORMULA_PATH}/reclass/service/*; do
              ln -s $formula /srv/salt/reclass/classes/service/`basename ${formula}`
            done

            [ ! -d /srv/salt/env ] && mkdir -p /srv/salt/env
            [ ! -L /srv/salt/env/prd ] && ln -s ${FORMULA_PATH}/env /srv/salt/env/prd

            [ ! -d /etc/reclass ] && mkdir /etc/reclass
            cat << 'EOF' > /etc/reclass/reclass-config.yml
            storage_type: yaml_fs
            pretty_print: True
            output: yaml
            inventory_base_uri: /srv/salt/reclass
            EOF

            echo "Configuring salt minion ..."
            [ ! -d /etc/salt/minion.d ] && mkdir -p /etc/salt/minion.d
            cat << "EOF" > /etc/salt/minion.d/minion.conf
            id: $node_name
            master: 127.0.0.1
            EOF
            apt-get install -y salt-minion

            echo "Restarting services ..."
            systemctl restart salt-master
            systemctl restart salt-minion

            echo "Showing system info and metadata ..."
            salt-call --no-color grains.items
            salt-call --no-color pillar.data

            echo "Running complete state ..."
            salt-call --no-color state.sls linux,openssh -l info
            salt-call --no-color state.sls reclass -l info
            salt-call --no-color state.sls salt.master.service -l info
            salt-call --no-color state.sls salt.master,salt.api,salt.minion.ca -l info
            systemctl restart salt-minion

            reclass-salt --top
            salt-call --no-color state.sls salt.minion.cert -l info
            $wait_condition_notify --data-binary '{"status": "SUCCESS"}'
          params:
            $node_name: { get_param: ci01_name }
            $config_host: localhost
            $wait_condition_notify: { get_attr: [ci01_wait_handle, curl_cli] }
            $key_private: { get_param: key_private }
            $reclass_address: { get_param: reclass_address }
            $reclass_branch: { get_param: reclass_branch }
  ci02_private_port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_param: private_net }
      fixed_ips:
        - ip_address: { get_param: ci02_address }
      allowed_address_pairs:
        - ip_address: { get_param: cluster_vip_address }
      security_groups:
        - default
        - { get_param: security_group }
  ci02_wait_handle:
    type: OS::Heat::WaitConditionHandle
  ci02_wait_condition:
    type: OS::Heat::WaitCondition
    properties:
      handle: {get_resource: ci02_wait_handle}
      timeout: 3600
  ci02_instance:
    type: OS::Nova::Server
    depends_on: ci01_wait_condition
    properties:
      image: { get_param: instance_image }
      flavor: { get_param: instance_flavor }
      key_name: { get_param: key_pair }
      name: { get_param: ci02_name }
      availability_zone: { get_param: instance_zone }
      networks:
      - port: { get_resource: ci02_private_port }
      user_data_format: RAW
      user_data:
        str_replace:
          template: |
            #!/bin/bash
            echo "Preparing base OS ..."
            echo "nameserver 8.8.8.8" >/etc/resolv.conf

            which wget >/dev/null || (apt-get update; apt-get install -y wget)

            echo "deb [arch=amd64] http://apt.tcpcloud.eu/nightly/ xenial main security extra tcp tcp-salt" > /etc/apt/sources.list
            wget -O - http://apt.tcpcloud.eu/public.gpg | apt-key add -

            echo "deb http://repo.saltstack.com/apt/ubuntu/16.04/amd64/2016.3 xenial main" > /etc/apt/sources.list.d/saltstack.list
            wget -O - https://repo.saltstack.com/apt/ubuntu/16.04/amd64/2016.3/SALTSTACK-GPG-KEY.pub | apt-key add -

            apt-get clean
            apt-get update
            apt-get install -y salt-minion

            echo "id: $node_name" >> /etc/salt/minion
            echo "master: $config_host" >> /etc/salt/minion
            rm -f /etc/salt/pki/minion/minion_master.pub
            service salt-minion restart
            echo "Showing node metadata..."
            salt-call --no-color pillar.data
            echo "Running complete state ..."
            salt-call --no-color state.sls linux,openssh,salt -l info
            $wait_condition_notify --data-binary '{"status": "SUCCESS"}'
          params:
            $node_name: { get_param: ci02_name }
            $config_host: { get_param: ci01_address }
            $wait_condition_notify: { get_attr: [ci02_wait_handle, curl_cli] }
  ci03_private_port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_param: private_net }
      fixed_ips:
        - ip_address: { get_param: ci03_address }
      allowed_address_pairs:
        - ip_address: { get_param: cluster_vip_address }
      security_groups:
        - default
        - { get_param: security_group }
  ci03_wait_handle:
    type: OS::Heat::WaitConditionHandle
  ci03_wait_condition:
    type: OS::Heat::WaitCondition
    properties:
      handle: {get_resource: ci03_wait_handle}
      timeout: 3600
  ci03_instance:
    type: OS::Nova::Server
    depends_on: ci01_wait_condition
    properties:
      image: { get_param: instance_image }
      flavor: { get_param: instance_flavor }
      key_name: { get_param: key_pair }
      name: { get_param: ci03_name }
      availability_zone: { get_param: instance_zone }
      networks:
      - port: { get_resource: ci03_private_port }
      user_data_format: RAW
      user_data:
        str_replace:
          template: |
            #!/bin/bash
            echo "Preparing base OS ..."
            echo "nameserver 8.8.8.8" >/etc/resolv.conf

            which wget >/dev/null || (apt-get update; apt-get install -y wget)

            echo "deb [arch=amd64] http://apt.tcpcloud.eu/nightly/ xenial main security extra tcp tcp-salt" > /etc/apt/sources.list
            wget -O - http://apt.tcpcloud.eu/public.gpg | apt-key add -

            echo "deb http://repo.saltstack.com/apt/ubuntu/16.04/amd64/2016.3 xenial main" > /etc/apt/sources.list.d/saltstack.list
            wget -O - https://repo.saltstack.com/apt/ubuntu/16.04/amd64/2016.3/SALTSTACK-GPG-KEY.pub | apt-key add -

            apt-get clean
            apt-get update
            apt-get install -y salt-minion

            echo "id: $node_name" >> /etc/salt/minion
            echo "master: $config_host" >> /etc/salt/minion
            rm -f /etc/salt/pki/minion/minion_master.pub
            service salt-minion restart
            echo "Showing node metadata..."
            salt-call --no-color pillar.data
            echo "Running complete state ..."
            salt-call --no-color state.sls linux,openssh,salt -l info
            $wait_condition_notify --data-binary '{"status": "SUCCESS"}'
          params:
            $node_name: { get_param: ci03_name }
            $config_host: { get_param: ci01_address }
            $wait_condition_notify: { get_attr: [ci03_wait_handle, curl_cli] }

outputs:
  config_host:
    value: { get_attr: [ci01_instance, first_address] }
    description: "Private IP address of the Salt master node"
  config_public:
    value: { get_attr: [ci01_floating_ip, ip] }
    description: "Public IP address of the Salt master node"
