heat_template_version: 2015-10-15

description: Jenkins master

parameters:

  public_net:
    type: string
  private_net:
    type: string

  security_group:
    type: string
  key_pair:
    type: string
  config_host:
    type: string
  private_key:
    type: string
    hidden: true

  instance_flavor:
    type: string
  instance_image:
    type: string
  instance_zone:
    type: string

  config_host:
    type: string
    default: 172.16.10.100

  cid01_name:
    type: string
  cid01_address:
    type: string
    default: 172.16.10.110

resources:
  cid01_floating_ip:
    type: OS::Nova::FloatingIP
    properties:
      pool: { get_param: public_net }
  cid01_floating_ip_association:
    type: OS::Nova::FloatingIPAssociation
    properties:
      floating_ip: { get_resource: cid01_floating_ip }
      server_id: { get_resource: cid01_instance }
  cid01_port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_param: private_net }
      fixed_ips:
        - ip_address: 172.16.10.110
      security_groups:
      - default
      - { get_param: security_group }
  cid01_volume:
    type: OS::Cinder::Volume
    properties:
      name: { get_param: cid01_name }
      size: 20
      image: { get_param: instance_image }
      volume_type: { get_param: volume_type }
  cid01_instance:
    type: OS::Nova::Server
    properties:
      block_device_mapping:
      - volume_id: { get_resource: cid01_volume }
        device_name: vda
      flavor: { get_param: instance_flavor }
      key_name: { get_param: key_pair }
      availability_zone: { get_param: availability_zone }
      name: { get_param: cid01_name }
      networks:
      - port: { get_resource: cid01_port }  
      user_data_format: RAW
      user_data:
        str_replace:
          template: |
            #!/bin/bash -x

            # tmp workaround missing configuration on FW
            ip link set mtu 1400 dev eth0

            which wget >/dev/null || (apt-get update; apt-get install -y wget)

            echo "deb [arch=amd64] http://10.167.4.94/ubuntu-trusty nightly tcp salt" > /etc/apt/sources.list
            wget -O - http://10.167.4.94/public.gpg | apt-key add -

            ssh-keyscan -H romulus.st.sk >> /root/.ssh/known_hosts
            ssh-keyscan -H 10.167.4.93 >> /root/.ssh/known_hosts

            mkdir -p /etc/salt/minion.d
            echo "id: $node_name" >> /etc/salt/minion.d/minion.conf
            echo "master: $config_host" >> /etc/salt/minion.d/minion.conf

            apt-get clean
            apt-get update
            apt-get install -y salt-minion
            apt-get install -y git
            
            export HOME=/root
            git config --global http.sslVerify false

            salt-call pillar.data
            salt-call state.sls linux,openssh,salt -l info
            salt-call state.highstate -l info

            ssh-keyscan -H romulus.st.sk >> /var/lib/jenkins/.ssh/known_hosts
            ssh-keyscan -H 172.16.10.100 >> /var/lib/jenkins/.ssh/known_hosts

            sleep 30

            ##Create temporal folder

            TMP_DIR=/tmp/cert
            CA_FILE=ca_emeldi.pem

            mkdir -p $TMP_DIR

            # Create CA File

            cat > $TMP_DIR/$CA_FILE <<- EOM
            $private_key
            EOM

            # Install and Update CA Certificates

            openssl x509 -outform der -in $CA_FILE -out $TMP_DIR/$(echo $CA_FILE | cut -d. -f1).crt
            cp $JAVA_HOME/jre/lib/security/cacerts $JAVA_HOME/jre/lib/security/cacerts.old
            keytool -import -trustcacerts -keystore $JAVA_HOME/jre/lib/security/cacerts -storepass changeit -noprompt -alias $(echo $CA_FILE | cut -d. -f1) -file $TMP_DIR/$(echo $CA_FILE | cut -d. -f1).crt
            cp /etc/ssl/certs/java/cacerts /etc/ssl/certs/java/cacerts.old
            keytool -import -trustcacerts -keystore  /etc/ssl/certs/java/cacerts -storepass changeit -noprompt -alias $(echo $CA_FILE | cut -d. -f1) -file $TMP_DIR/$(echo $CA_FILE | cut -d. -f1).crt
            cp $TMP_DIR/$CA_FILE /usr/share/ca-certificates/mozilla/
            update-ca-certificates

            service jenkins stop
            sleep 10
            service jenkins start
            sleep 10

            mvn install:install-file -DgroupId=com.oracle -DartifactId=ojdbc6 -Dversion=11.2.0.3 -Dpackaging=jar -Dfile=ojdbc6.jar -DgeneratePom=true

            count=1;
            until [  `curl -s -o /dev/null -I -w "%{http_code}" http://127.0.0.1:8080` -lt "303" ]; do
              echo "Starting Jenkins, try $count";
              (( count++ ))
              sleep 10
            done

            salt-call state.sls jenkins.client -l info
            sleep 10
            salt-call state.sls jenkins.client -l info
          params:
            $node_name: { get_param: cid01_name }
            $private_key: { get_param: private_key }
            $config_host: { get_param: config_host }

outputs:
  config_host:
    value: { get_attr: [cid01_instance, first_address] }
    description: "Private IP address of the Jenkins master node"
