heat_template_version: 2013-05-23

description: OpenStack support fragment

parameters:

  private_net:
    type: string
  security_group:
    type: string
  key_pair:
    type: string
  config_host:
    type: string

  instance_flavor:
    type: string
  instance_image:
    type: string
  instance_zone:
    type: string

  mon01_name:
    type: string

resources:

  mon01_port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_param: private_net }
      fixed_ips:
        - ip_address: 172.16.10.107
      security_groups:
        - default
        - { get_param: security_group }
  mon01_instance:
    type: OS::Nova::Server
    properties:
      image: { get_param: instance_image }
      flavor: { get_param: instance_flavor }
      key_name: { get_param: key_pair }
      name: { get_param: mon01_name }
      availability_zone: { get_param: instance_zone }
      networks:
      - port: { get_resource: mon01_port }
      user_data_format: RAW
      user_data:
        str_replace:
          template: |
            #!/bin/bash
            echo "Preparing base OS"
            which wget >/dev/null || (apt-get update; apt-get install -y wget)

            echo "deb [arch=amd64] http://apt.tcpcloud.eu/nightly/ trusty main security extra tcp tcp-salt" > /etc/apt/sources.list
            wget -O - http://apt.tcpcloud.eu/public.gpg | apt-key add -

            apt-get clean
            apt-get update
            apt-get install -y salt-minion

            echo "id: $node_name" >> /etc/salt/minion
            echo "master: $config_host" >> /etc/salt/minion
            rm -f /etc/salt/pki/minion/minion_master.pub
            service salt-minion restart
            echo "Showing node metadata..."
            salt-call --no-color pillar.data
            echo "Running complete state ..."
            salt-call --no-color state.sls linux,openssh,salt
          params:
            $node_name: { get_param: mon01_name }
            $config_host: { get_param: config_host }
