heat_template_version: 2015-10-15

description: 2 same nodes

parameters:
  admin_net:
    type: string
  private_net:
    type: string
  external_net:
    type: string
  tenant_net:
    type: string
  security_group:
    type: string
  key_pair:
    type: string
  config_host:
    type: string
  instance_flavor:
    type: string
  instance_image:
    type: string
  instance_zone:
    type: string
  instance_os:
    type: string
  instance01_name:
    type: string
  private_instance01_address:
    type: string
  tenant_instance01_address:
    type: string
  external_instance01_address:
    type: string
  instance02_name:
    type: string
  private_instance02_address:
    type: string
  tenant_instance02_address:
    type: string
  external_instance02_address:
    type: string

resources:
  instance01:
    type: MCP::ServerInstance4
    properties:
      admin_net: { get_param: admin_net }
      private_net: { get_param: private_net }
      external_net: { get_param: external_net }
      tenant_net: { get_param: tenant_net }
      key_pair: { get_param: key_pair }
      security_group: { get_param: security_group }
      config_host: { get_param: config_host }
      instance_os: { get_param: instance_os }
      instance_flavor: { get_param: instance_flavor }
      instance_image: { get_param: instance_image }
      instance_zone:  { get_param: instance_zone }
      instance_name: { get_param: instance01_name }
      private_instance_address: { get_param: private_instance01_address }
      tenant_instance_address: { get_param: tenant_instance01_address }
      external_instance_address: { get_param: external_instance01_address }
  instance02:
    type: MCP::ServerInstance4
    properties:
      admin_net: { get_param: admin_net }
      private_net: { get_param: private_net }
      external_net: { get_param: external_net }
      tenant_net: { get_param: tenant_net }
      key_pair: { get_param: key_pair }
      security_group: { get_param: security_group }
      config_host: { get_param: config_host }
      instance_os: { get_param: instance_os }
      instance_flavor: { get_param: instance_flavor }
      instance_image: { get_param: instance_image }
      instance_zone:  { get_param: instance_zone }
      instance_name: { get_param: instance02_name }
      private_instance_address: { get_param: private_instance02_address }
      tenant_instance_address: { get_param: tenant_instance02_address }
      external_instance_address: { get_param: external_instance02_address }

