heat_template_version: 2015-10-15

description: Server cluster (3 nodes static with policy)

parameters:
  admin_net:
    type: string
  private_net:
    type: string
  security_group:
    type: string
  key_pair:
    type: string
  config_host:
    type: string
  instance_flavor:
    type: string
  instance_image:
    type: string
  instance_zone:
    type: string
  instance_os:
    type: string
  instance_vip_address:
    type: string
  instance01_name:
    type: string
  instance01_address:
    type: string
  instance02_name:
    type: string
  instance02_address:
    type: string
  instance03_name:
    type: string
  instance03_address:
    type: string
  cluster_name:
    type: string
  cluster_policy:
    type: string
    default: 'anti-affinity'

resources:
  server_cluster_policy: 
    type: OS::Nova::ServerGroup
    properties: 
      name: { get_param: cluster_name }
      policies: [ { get_param: cluster_policy } ]
  instance01:
    type: MCP::PolicyClusterMember
    properties:
      admin_net: { get_param: admin_net }
      private_net: { get_param: private_net }
      key_pair: { get_param: key_pair }
      security_group: { get_param: security_group }
      config_host: { get_param: config_host }
      instance_os: { get_param: instance_os }
      instance_flavor: { get_param: instance_flavor }
      instance_image: { get_param: instance_image }
      instance_zone:  { get_param: instance_zone }
      instance_name: { get_param: instance01_name }
      cluster_name: { get_param: cluster_name }
      instance_vip_address: { get_param: instance_vip_address }
  instance02:
    type: MCP::PolicyClusterMember
    properties:
      admin_net: { get_param: admin_net }
      private_net: { get_param: private_net }
      key_pair: { get_param: key_pair }
      security_group: { get_param: security_group }
      config_host: { get_param: config_host }
      instance_os: { get_param: instance_os }
      instance_flavor: { get_param: instance_flavor }
      instance_image: { get_param: instance_image }
      instance_zone:  { get_param: instance_zone }
      instance_name: { get_param: instance02_name }
      cluster_name: { get_param: cluster_name }
      instance_vip_address: { get_param: instance_vip_address }
  instance03:
    type: MCP::PolicyClusterMember
    properties:
      admin_net: { get_param: admin_net }
      private_net: { get_param: private_net }
      key_pair: { get_param: key_pair }
      security_group: { get_param: security_group }
      config_host: { get_param: config_host }
      instance_os: { get_param: instance_os }
      instance_flavor: { get_param: instance_flavor }
      instance_image: { get_param: instance_image }
      instance_zone:  { get_param: instance_zone }
      instance_name: { get_param: instance03_name }
      cluster_name: { get_param: cluster_name }
      instance_vip_address: { get_param: instance_vip_address }
