heat_template_version: 2015-10-15

description: Single service instance [unmanaged]

parameters:
  admin_net:
    type: string
  private_net:
    type: string
  security_group:
    type: string
  key_pair:
    type: string
  instance_name:
    type: string
  instance_os:
    type: string
  instance_address:
    type: string
  instance_flavor:
    type: string
  instance_image:
    type: string
  instance_zone:
    type: string

resources:
  instance_port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_param: private_net }
      fixed_ips:
        - ip_address: { get_param: instance_address }
      security_groups:
        - default
        - { get_param: security_group }
  instance_instance:
    type: OS::Nova::Server
    properties:
      image: { get_param: instance_image }
      image_update_policy: REBUILD
      flavor: { get_param: instance_flavor }
      name: { get_param: instance_name }
      availability_zone: { get_param: instance_zone }
      key_name: { get_param: key_pair }
      networks:
      - network: { get_param: admin_net }
      - port: { get_resource: instance_port }

outputs:
  instance_address:
    value: { get_attr: [instance_instance, first_address] }
    description: "Instance's private IP address"
