heat_template_version: 2015-10-15

description: >
  Telekom network resources

parameters:

  param_instance_name:
    type: string
    description: The name of instance

  param_stack_type:
    type: string
    description: provide the stack type
    default: automation-team

  param_stack_name:
    type: string
    description: provide the stack name

  param_instance_floating_ip:
    type: string
    description: standard domain name for cloud - dont change install_salt

  param_virtual_DNS:
    type: string
    description: virtual_DNS for the VirtualDnsRecord

  virtual_DNS_record_data_record_ttl_seconds:
    type: number
    description: standard domain name for cloud - dont change install_salt
    default: 600

  virtual_DNS_record_data_record_type:
    type: string
    description: record_type for the VirtualDnsRecord
    default: A

  virtual_DNS_record_data_record_class:
    type: string
    description: record_class for the VirtualDnsRecord
    default: IN

  virtual_DNS_record_data_record_mx_preference:
    type: number
    description: record_mx_preference for the VirtualDnsRecord
    default: 1

resources:
  telekom-dns-record:
    type: OS::ContrailV2::VirtualDnsRecord
    properties:
      name: {list_join: ['.', [ { get_param: param_instance_name}, { get_param: param_stack_name } , {get_param: param_stack_type}] ]}
      fq_name:  {list_join: [':', [ 'default-domain' , {get_param: param_virtual_DNS} ] ]}
      virtual_dns_record_data:
        {
          virtual_dns_record_data_record_name: {list_join: ['.', [ { get_param: param_instance_name}, { get_param: param_stack_name } , {get_param: param_stack_type}] ]},
          virtual_dns_record_data_record_type: { get_param: virtual_DNS_record_data_record_type },
          virtual_dns_record_data_record_class: { get_param: virtual_DNS_record_data_record_class },
          virtual_dns_record_data_record_data:  {get_param: param_instance_floating_ip },
          virtual_dns_record_data_record_ttl_seconds: { get_param: virtual_DNS_record_data_record_ttl_seconds },
          virtual_dns_record_data_record_mx_preference: { get_param: virtual_DNS_record_data_record_mx_preference },
        }
      display_name: {list_join: ['.', [ { get_param: param_instance_name}, { get_param: param_stack_name } , {get_param: param_stack_type}] ]}
      virtual_dns: {list_join: [':', [ 'default-domain' , {get_param: param_virtual_DNS} ] ]}

########################################################################################################################################x
##            REVERSE RECORD
## This section will be create reverse vDNS record
## @Param:
##       {string} name:                                   Floating IP of instance 
##       {string} fq_name:                                Name of DNS            ;;example: default-domain:tenant001-onlinedev-FIP-vDNS 
##       {string} virtual_dns_record_data_record_name:    Floating IP of instance 
##       {string} virtual_dns_record_data_record_type:    For reverse recored use 'PTR' 
##       {string} virtual_dns_record_data_record_class:   For reverse recored use 'IN' 
##       {string} virtual_dns_record_data_record_data:    Please use the instance name 
##       {number} virtual_dns_record_data_record_ttl_seconds:    TTL seconds - standard 600 
##       {number} virtual_dns_record_data_record_mx_preference:    Use standard 1


  telekom-dns-record-reverse:
    type: OS::ContrailV2::VirtualDnsRecord
    properties:

      name: {get_param: param_instance_floating_ip }
      fq_name:  {list_join: [':', [ 'default-domain' , {get_param: param_virtual_DNS} ] ]}
      virtual_dns_record_data:
        {
          virtual_dns_record_data_record_name: {get_param: param_instance_floating_ip },
          virtual_dns_record_data_record_type: 'PTR',
          virtual_dns_record_data_record_class: { get_param: virtual_DNS_record_data_record_class },
          virtual_dns_record_data_record_data:  { get_param: param_instance_name},
          virtual_dns_record_data_record_ttl_seconds: { get_param: virtual_DNS_record_data_record_ttl_seconds },
          virtual_dns_record_data_record_mx_preference: { get_param: virtual_DNS_record_data_record_mx_preference },
        }
      display_name: {get_param: param_instance_floating_ip }
      virtual_dns: {list_join: [':', [ 'default-domain' , {get_param: param_virtual_DNS} ] ]}