heat_template_version: 2015-10-15

description: Single service instance fragment [unmanaged]

parameters:
  key_pair:
    type: string
  network:
    type: string
  security_group:
    type: string
  deploy_subnet_prefix:
    type: string
  control_subnet_prefix:
    type: string
  tenant_subnet_prefix:
    type: string
  external_subnet_prefix:
    type: string
  instance_name:
    type: string
  instance_domain:
    type: string
  instance_cluster:
    type: string
  instance_zone:
    type: string
  instance_os:
    type: string
  instance_flavor:
    type: string
  instance_image:
    type: string
  instance_cloud_init:
    type: string
    default: ""

resources:
  instance_port01:
    type: OS::Neutron::Port
    properties:
      network_id: { list_join: ['-', [get_param: network, 'net01']] }
      security_groups:
        - default
        - { get_param: security_group }
  instance_port02:
    type: OS::Neutron::Port
    properties:
      network_id: { list_join: ['-', [get_param: network, 'net02']] }
      security_groups:
        - default
        - { get_param: security_group }
  instance_port03:
    type: OS::Neutron::Port
    properties:
      network_id: { list_join: ['-', [get_param: network, 'net03']] }
      security_groups:
        - default
        - { get_param: security_group }
  instance_port04:
    type: OS::Neutron::Port
    properties:
      network_id: { list_join: ['-', [get_param: network, 'net04']] }
      security_groups:
        - default
        - { get_param: security_group }
  instance_wait_handle:
    type: OS::Heat::WaitConditionHandle
  instance_wait_condition:
    type: OS::Heat::WaitCondition
    properties:
      handle: {get_resource: instance_wait_handle}
      timeout: 3600
  instance_instance:
    type: OS::Nova::Server
    properties:
      image: { get_param: instance_image }
      image_update_policy: REBUILD
      flavor: { get_param: instance_flavor }
      name:
        list_join:
        - '.'
        - [ { get_param: instance_name }, { get_param: instance_domain } ]
      availability_zone: { get_param: instance_zone }
      key_name: { get_param: key_pair }
      networks:
      - port: { get_resource: instance_port01 }
      - port: { get_resource: instance_port02 }
      - port: { get_resource: instance_port03 }
      - port: { get_resource: instance_port04 }
      user_data_format: RAW
      user_data:
        str_replace:
          template: { get_file: ../script/service_instance_boot.sh }
          params:
            $deploy_subnet_prefix: { get_param: deploy_subnet_prefix }
            $control_subnet_prefix: { get_param: control_subnet_prefix }
            $tenant_subnet_prefix: { get_param: tenant_subnet_prefix }
            $external_subnet_prefix: { get_param: external_subnet_prefix }
            $instance_cloud_init: { get_param: instance_cloud_init }
            $wait_condition_notify: { get_attr: [instance_wait_handle, curl_cli] }
outputs:
  instance_address:
    value: { get_attr: [instance_instance, first_address] }
    description: "Instance's private IP address"
  instance:
    value: { get_resource: instance_instance }
    description: "Instance"
